// <auto-generated />
namespace assignment_2_task_6.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class adas : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(adas));
        
        string IMigrationMetadata.Id
        {
            get { return "202105250449512_adas"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
